[deps]
ColorBitstring = "ce91de38-7578-4b98-aebb-6a5df05791d6"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
