name = "MATH50003NumericalAnalysis"
uuid = "9f559201-c820-4d08-baf1-f1369a1016bd"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ColorBitstring = "ce91de38-7578-4b98-aebb-6a5df05791d6"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Interact = "c601a237-2ae4-5e1e-952c-7a85b0c7eef1"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SetRounding = "3cc68bcd-71a2-5612-b932-767ffbe40ab0"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
